name: "Test to run workflow manually v13"

on:
  workflow_dispatch:
    inputs:
      instance_size:
        description: "Enter AWS credential"
        required: true
        type: choice
        default: "t3.micro"
        options:
          - t3.micro
          - t3.small
          - t3.medium
    
jobs:
  provision-infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: "Echo AWS instance size"
        run: echo "Provisioning AWS instance of size ${{ inputs.instance_size }}"

