name: "Test to run workflow manually"

on:
  workflow_dispatch:
    
jobs:
  provision-infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: "Echo AWS instance size"
        run: echo "Provisioning AWS instance of size"

